### ISSUE TITLE
Add tabs functionality to panels

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-panels#28]
I think that adding the ability to turn `panels` into tabs (e.g., via `tabs: true`) could be a relatively straightforward way to extend this directive for a common use-case. For example, it seems pretty doable in Bootstrap:

https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp  (search for "Dynamic tabs")

I'd imagine we could piggy-back on our pre-existing syntax like so:

````
```{panels}
Panel 1 title
^^^^^^^^^^^^^

Panel 1 content
---
Panel 2 title
^^^^^^^^^^^^^

Panel 2 content
```
````

would map onto the following tabs structure:

````
```{panels}
:tabs:
Tab 1 title
^^^^^^^^^^^

Tab 1 content
---
Tab 2 title
^^^^^^^^^^^

Tab 2 content
```
````

What do you think? Then we could recommend this pattern for tabs instead of using `sphinx-tabs` (which IME has been a bit buggy)

**Comment by chrisjsewell** [comment]
Note that particularly now that sphinx-tabs is part of the EBP family, we have more scope to think about a "merge" of that and toggle-buttons.

The only sticking point is that, currently, this package is "CSS based" only, which I like because it requires no JavaScript loads (which can slow down page loads) and obviously works when offline or when JS is deactivated.
Whereas toggle-buttons and tabs currently rely on JS.
This is especially acute with the current situation, whereby I haven't seen any "simple" way to make sphinx only include JS in the pages it is required (i.e. those that contain a certain directives), and not just every page.

**Comment by chrisjsewell** [comment]
I'm sure I talked about this in another issue somewhere (but I can't remember which one or which repo!).
But there are approaches like https://css-tricks.com/the-checkbox-hack/
But perhaps it called a hack for a reason 😬

**Comment by chrisjsewell** [comment]
See e.g. https://gomakethings.com/when-to-use-css-vs.-javascript/

**Comment by chrisjsewell** [comment]
@pradyunsg perhaps you have thoughts on this, in relation to https://github.com/executablebooks/sphinx-tabs/issues/87

**Comment by stefanodavid** [comment]
> This is especially acute with the current situation, whereby I haven't seen any "simple" way to make sphinx only include JS in the pages it is required (i.e. those that contain a certain directives), and not just every page.

Just another guess: what about using the `extrahead` template? I know there is a way to tell Jinja to include some part of the template only if a condition is true. But I admit I have no idea how to set up this condition in the source code and let it be read from the template...

**Comment by chrisjsewell** [comment]
Note I have opened https://github.com/executablebooks/meta/issues/119 for a general discussion of including JS in specific pages.

**Comment by pradyunsg** [comment]
>  But there are approaches like [css-tricks.com/the-checkbox-hack](https://css-tricks.com/the-checkbox-hack/)

Well, this is super effective IMO. That's what I'm using in my as-yet-unnamed theme that I've been teasing here and there. :)

**Comment by pradyunsg** [comment]
>  This is especially acute with the current situation, whereby I haven't seen any "simple" way to make sphinx only include JS in the pages it is required (i.e. those that contain a certain directives), and not just every page.

About that, I have a semi-hacky idea for this -- a new Sphinx plugin/extension that plugs into Sphinx's html-page-context event. The user provides a dictionary of `{selector: [scripts]}`. The plugin reads the `context["body"]`, checks if there's no elements that match the selector, then we .pop() out the corresponding scripts from the page's `context["script_files"]`. :)

```py
html_trim_javascript = {
    ".math": ["/path/of/Mathjax.js"]
}
```

**Comment by akhmerov** [comment]
This seems like a useful mechanism to upstream.

**Comment by pradyunsg** [comment]
> you have thoughts on this, in relation to [executablebooks/sphinx-tabs#87](https://github.com/executablebooks/sphinx-tabs/issues/87)

Hmm... it'd be nice to have something for tabs in Sphinx documentation that's not including an entire CSS framework (or substantial chunks of it). It may be "reasonably" easy to implement something for tabs without having a 100s of rules of CSS from some framework included.

At the end of the day, I want something like https://squidfunk.github.io/mkdocs-material/reference/content-tabs/ in Sphinx documentation -- as clean and lightweight in the output.

---

If I were making a checklist for how a sphinx-tabs v2 or some alternative works:

- CSS-only implementation
- no dependencies on CSS frameworks
- good-looking out-of-the-box, with theme authors being able to customize styling (this is, well, a consequence of the two above -- just add a bunch of rules w/ higher specificity)

We don't have anything today that checks all these boxes effectively. :(

**Comment by chrisjsewell** [comment]
You don't have to include bootstrap in sphinx-panels, just: `panels_add_boostrap_css = False`

**Comment by pradyunsg** [comment]
FWIW, I was referencing sphinx-tabs including semantic-ui. :)

**Comment by chrisjsewell** [comment]
Fair 😄 Definitely room for improvement in sphinx-panels, but I'd definitely like to add the CSS tabs here, and we can think about making it less CSS heavy.

btw, I note that Firefox is showing me sass in the style editor. How does that work? I was led to believe that sass had to be compiled?

![image](https://user-images.githubusercontent.com/2997570/91726724-9b394700-eb98-11ea-934e-257f53beb7a5.png)

**Comment by pradyunsg** [comment]
> How does that work? I was led to believe that sass had to be compiled?

sourcemaps -- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map!

**Comment by chrisjsewell** [comment]
Ah cool cheers, learn something new every day 😄

**Comment by pradyunsg** [comment]
Looks like the things we'd want to do are:

- Implement tabs in sphinx-panels.
- Write a plugin for conditional includes.
- Add a mechanism upstream for conditional includes.
- Deprecate/kill sphinx-tabs?

What order do we want to do these things in?

**Comment by chrisjsewell** [comment]
> Write a plugin for conditional includes

Can you re-clarify what you mean by this? As in only loading the CSS on certain pages

> Deprecate/kill sphinx-tabs?

I think just put a notice+link in the sphinx-tabs documentation, that there is also an implementation here, and explain that one uses JS/CSS and the other just CSS which both have their pros and cons (we shall have to see if everything in sphinx-tabs can be achieved *via* CSS)

**Comment by chrisjsewell** [comment]
> Write a plugin for conditional includes

Can you re-clarify what you mean by this? As in only loading the CSS on certain pages

> Deprecate/kill sphinx-tabs?

I think just put a notice+link in the sphinx-tabs documentation, that there is also an implementation here, and explain that one uses JS/CSS and the other just CSS which both have their pros and cons (we shall have to see if everything in sphinx-tabs can be achieved *via* CSS)

**Comment by pradyunsg** [comment]
Oh, I thought we were "blending" sphinx-tabs into this package. :)

What you're saying makes total sense then.

> Can you re-clarify what you mean by this? As in only loading the CSS on certain pages?

It was a thing discussed here, so I'm trying to figure out how high we prioritize it in terms of "things we do, given the limited amount of time we all have".

**Comment by pradyunsg** [comment]
(if you're following this thread by email, you're probably *very* happy about my edits-immediately-after-posting behavior 🥰)

**Comment by akhmerov** [comment]
> Write a plugin for conditional includes.

Please consider making this a standalone plugin seems super-useful :pray:

**Comment by chrisjsewell** [comment]
Well, unconditional includes of local CSS (if properly specified) isn't as much of an issue as for JS, so I would put that as lower priority.
(I would imagine it wouldn't be too hard to extend later on though)

**Comment by pradyunsg** [comment]
>  (I would imagine it wouldn't be too hard to extend later on though)

It's "just" a second loop in the plugin for going through `css_files` in addition to `script_files`. Wouldn't be *that* difficult. :)

> Please consider making this a standalone plugin seems super-useful 🙏

Oh, 100%. I'm definitely thinking that this should be a separate plugin.

**Comment by choldgraf** [comment]
+1 to a conditional-includes package...that'd be quite useful

**Comment by chrisjsewell** [comment]
fixed in #32
Take your pick:

- https://sphinx-panels.readthedocs.io/en/latest/#tabbed-content
- https://sphinx-panels.readthedocs.io/en/sphinx-book-theme/#tabbed-content
- https://sphinx-panels.readthedocs.io/en/pydata-theme/#tabbed-content
- https://sphinx-panels.readthedocs.io/en/alabaster-theme/#tabbed-content

Obviously can iterate on any added functionality / styling

**Comment by pradyunsg** [comment]
Looks great, yay!

**Comment by pradyunsg** [comment]
We should add this to the README.

**Comment by chrisjsewell** [comment]
Add what? You shouldn’t need anything in the readme it’s all in the docs

**Comment by pradyunsg** [comment]
As in, an example of tabbed in the README, since we mention panels and dropdowns there.

**Comment by chrisjsewell** [comment]
thats legacy really, I'd be more inclined to delete those from the README, point towards the documentation, and just include the bullet points:

- The ``panels`` directive creates panels of content in a grid layout, utilising both the bootstrap 4
  `grid system <https://getbootstrap.com/docs/4.0/layout/grid/>`_,
  and `cards layout <https://getbootstrap.com/docs/4.0/components/card/>`_.
- The ``link-button`` directive creates a click-able button, linking to a URL or reference,
  and can also be used to make an entire panel click-able.
- The ``dropdown`` directive creates toggle-able content.
- The ``tabbed`` directive creates tabbed content.
- ``opticon`` and ``fa`` roles allow for inline icons to be added.

**Comment by chrisjsewell** [comment]
Its a bit pointless showing the directives, without the resulting web components

**Comment by jorisvandenbossche** [comment]
I think such a summary bullet list of features would indeed be good for the README, agreed that showing the actual directive code is not that useful. It's more interesting to show what it can do, than how it achieves it (so I would maybe include one picture of some output as teaser in addition to the bullet points)

**Comment by pradyunsg** [comment]
100% in agreement w/ @jorisvandenbossche!

**Comment by graingert** [comment]
wouldn't it be neater to do conditional includes client side, with:

```js
if (page == ".math") {
  const {default: Mathjax} = await import("./Mathjax.mjs");
}
```

**Comment by pradyunsg** [comment]
If only Sphinx let us customize how the pages include these scripts work, to that extent.

FWIW, since we're also capable of parsing the document's generated HTML, it probably makes sense to have an overhead at compile instead of runtime for this, since it's static-information-on-a-per-page-basis anyway. :)
