### ISSUE TITLE
Override CSS for `.container` instead of adding a div directive

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-panels#38]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to use `.. div::` instead of `.. container::` when using this package. This is unacceptable! 😜 

**Describe the solution you'd like**

Change how this package is implemented by overriding bootstrap's CSS for the container class to remove/change the padding and max-width styling, instead of introducing specific directives to work around them.

**Describe alternatives you've considered**

Status quo?

**Additional context**

I'm annoyed at Reddit's r/programming while I'm writing this issue. Apologies for the terseness.

**Comment by chrisjsewell** [comment]
This is not really an issue with sphinx-panels, it is an issue with docutils adding an unnecessary an over generalised `container` class. You should raise it with them.
I would entertain PRs, but otherwise, this is not something that I will be looking to change.
