### ISSUE TITLE
Simplify configuration for quick access to common setups

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-panels#45]
**Is your feature request related to a problem? Please describe.**

I just gave `sphinx-panels` a go and found it very difficult to understand the `grid system` and `card layout` documentation not having a lot of exposure to `html` / `css` etc. I tried:

``````
````{panels}
```{figure} _static/logo1.png
```
---
```{figure} _static/logo2.png
```
````
``````

but it came up as `2 rows x 1 column` when I thought from the docs it would be `1 row x 2 columns`

**Describe the solution you'd like**

This is similar to #18 -- but I think it would be great to simplify access to high level configurations such as an equally spaced grid with `:rows:` and `:columns:` able to be provided. 

**Describe alternatives you've considered**

None -- other than learning the complex juganaut that is `.col-sm-4` magic

**Comment by chrisjsewell** [comment]
> but it came up as 2 rows x 1 column when I thought from the docs it would be 1 row x 2 columns

This feels like a misunderstanding of how panels actually work; the number of columns is not fixed, it is dependant on screen/window. What happens if you increase the size of your viewing window?

**Comment by AakashGfude** [comment]
@chrisjsewell the `sphinx-panels` in the case of @mmcky was tested with `quantecon-book-theme` which does not use bootstrap. So, on inspecting the elements, none of the `col-md`, `col-xs` styles were applied. 
I reckon its a requirement of projects using `sphinx-panels` to have bootstrap included in their theme?

**Comment by chrisjsewell** [comment]
The required bootstrap css is included with this extension, unless you have specifically turned it off in your conf.py, which may be the case if you have copied that from sphinx-book-theme

**Comment by AakashGfude** [comment]
ooh, nice. so there is a config in `sphinx-book-theme` ? or `sphinx-panels` to turn on/off?

**Comment by chrisjsewell** [comment]
What's the link to your conf.py

**Comment by AakashGfude** [comment]
the lecture on which it is being tested in https://github.com/QuantEcon/lecture-python-programming.myst/blob/master/lectures/_config.yml 

and the theme repo: https://github.com/QuantEcon/quantecon-book-theme

**Comment by chrisjsewell** [comment]
Oh you are using it with jupyter-book. Then yes it is turned off: https://github.com/executablebooks/jupyter-book/blob/a47ff972ecdb39b349a46c2d3bc796e57e98f7b9/jupyter_book/config.py#L43

**Comment by AakashGfude** [comment]
Thanks a lot @chrisjsewell .

**Comment by mmcky** [comment]
ok thanks @chrisjsewell -- I might add something to the docs. I didn't understand how `panels` works :-)

**Comment by mmcky** [comment]
@chrisjsewell are you saying to get `panels` to work we need to add

```yaml
panels_add_boostrap_css: True
```

to top level of `_config.yml`?

It looks like this is all setup using `jupyter-book` from the docs. 

https://jupyterbook.org/content/content-blocks.html?highlight=panels#panels-and-dropdowns

**Comment by chrisjsewell** [comment]
No you have to add it under sphinx config

**Comment by mmcky** [comment]
Ok thanks @chrisjsewell makes sense.
