### ISSUE TITLE
Add support for Sphinx 4

### ISSUE THREAD

**Issue by lsaffre** [executablebooks/sphinx-panels#60]
Sphinx 4.0.0 beta has been released (https://github.com/sphinx-doc/sphinx/blob/4.0.x/CHANGES), but I cannot easily install it because pip then complains that sphinx-panels requires Sphinx<4.

**Comment by chrisjsewell** [comment]
Thanks @lsaffre, I've already opened this as in issue across all of our sphinx packages: https://github.com/executablebooks/meta/issues/306

**Comment by lsaffre** [comment]
Ah, great! I subscribed to that ticket. We can close this one.
